/* @file Данные тегов EMV. */

#pragma once

#include "Hardware/Common/Specifications.h"

//--------------------------------------------------------------------------------
namespace CEMVTags
{
	const int MSREquivalentData = 0xDFEF4D;

	class CData : public CDescription<int>
	{
	public:
		CData()
		{
			append(    0x42, "Issuer Identification Number (IIN)");
			append(    0x4F, "Application Identifier (ADF Name)");
			append(    0x50, "Application Label");
			append(    0x52, "Command to perform");
			append(    0x56, "Track 1 Data");
			append(    0x57, "Track 2 Equivalent Data");
			append(    0x5A, "Application Primary Account Number (PAN)");
			append(    0x5D, "Deleted (see 9D)");
			append(    0x6F, "File Control Information (FCI) Template");
			append(    0x61, "Application Template");
			append(    0x62, "File Control Parameters (FCP) Template");
			append(    0x70, "READ RECORD Response Message Template");
			append(    0x71, "Issuer Script Template 1");
			append(    0x72, "Issuer Script Template 2");
			append(    0x73, "Directory Discretionary Template");
			append(    0x77, "Response Message Template Format 2");
			append(    0x80, "Response Message Template Format 1");
			append(    0x81, "Amount, Authorised (Binary)");
			append(    0x82, "Application Interchange Profile (AIP)");
			append(    0x83, "Command Template");
			append(    0x84, "Dedicated File (DF) Name");
			append(    0x86, "Issuer Script Command");
			append(    0x87, "Application Priority Indicator");
			append(    0x88, "Short File Identifier (SFI)");
			append(    0x89, "Authorisation Code");
			append(    0x8A, "Authorization Response Code");
			append(    0x8A, "Authorisation Response Code (ARC)");
			append(    0x8C, "Card Risk Management Data Object List 1 (CDOL1)");
			append(    0x8D, "Card Risk Management Data Object List 2 (CDOL2)");
			append(    0x8E, "Cardholder Verification Method (CVM) List");
			append(    0x8F, "Certification Authority Public Key Index (PKI)");
			append(    0x90, "Issuer Public Key Certificate");
			append(    0x91, "Issuer Authentication Data");
			append(    0x92, "Issuer Public Key Remainder");
			append(    0x93, "Signed Application Data");
			append(    0x94, "Application File Locator (AFL)");
			append(    0x95, "Terminal Verification Results (TVR)");
			append(    0x97, "Transaction Certificate Data Object List (TDOL)");
			append(    0x98, "Transaction Certificate (TC) Hash Value");
			append(    0x99, "Transaction Personal Identification Number (PIN) Data");
			append(    0x99, "Transaction Personal Identification Number (PIN) Data");
			append(    0x98, "Transaction Certificate (TC) Hash Value");
			append(    0x9A, "Transaction Date (YYMMDD )");
			append(    0x9A, "Transaction Date");
			append(    0x9B, "Transaction Status Information");
			append(    0x9B, "Transaction Status Information");
			append(    0x9C, "Transaction Type");
			append(    0x9C, "Transaction Type");
			append(    0x9D, "Directory Definition File (DDF) Name");
			append(    0xA5, "File Control Information (FCI) Proprietary Template");
			append(    0xC3, "Card issuer action code -decline");
			append(    0xC4, "Card issuer action code -default");
			append(    0xC5, "Card issuer action code online");
			append(    0xC6, "PIN Try Limit");
			append(    0xC7, "CDOL 1 Related Data Length");
			append(    0xC8, "Card risk management country code");
			append(    0xC9, "Card risk management currency code");
			append(    0xCA, "Lower cummulative offline transaction amount");
			append(    0xCB, "Upper cumulative offline transaction amount");
			append(    0xCD, "Card Issuer Action Code (PayPass) – Default");
			append(    0xCE, "Card Issuer Action Code (PayPass) – Online");
			append(    0xCF, "Card Issuer Action Code (PayPass) – Decline");
			append(    0xD1, "Currency conversion table");
			append(    0xD2, "Integrated Data Storage Directory (IDSD)");
			append(    0xD3, "Additional check table");
			append(    0xD5, "Application Control");
			append(    0xD6, "Default ARPC response code");
			append(    0xD7, "Application Control (PayPass)");
			append(    0xD8, "AIP (PayPass)");
			append(    0xD9, "AFL (PayPass)");
			append(    0xDA, "Static CVC3-TRACK1");
			append(    0xDB, "Static CVC3-TRACK2");
			append(    0xDC, "IVCVC3-TRACK1");
			append(    0xDD, "IVCVC3-TRACK2");
			append(  0x5F20, "Cardholder Name");
			append(  0x5F24, "Application Expiration Date");
			append(  0x5F28, "Issuer Country Code");
			append(  0x5F2A, "Transaction Currency Code (Default: 08 40)");
			append(  0x5F2D, "Language Preference");
			append(  0x5F30, "Service Code");
			append(  0x5F34, "Application Primary Account Number (PAN) Sequence Number (PSN)");
			append(  0x5F36, "Transaction Currency Exponent");
			append(  0x5F3C, "Transaction Reference Currency Code");
			append(  0x5F3D, "Transaction Reference Currency Exponent");
			append(  0x5F50, "Issuer URL");
			append(  0x5F53, "International Bank Account Number (IBAN)");
			append(  0x5F54, "Bank Identifier Code (BIC)");
			append(  0x5F55, "Issuer Country Code (alpha2 format)");
			append(  0x5F56, "Issuer Country Code (alpha3 format)");
			append(  0x5F57, "Account Type Selection");
			append(  0x9F01, "Acquirer Identifier");
			append(  0x9F02, "Amount, Authorized (Numeric)");
			append(  0x9F03, "Amount, Other (Numeric)");
			append(  0x9F04, "Amount, Other (Binary)");
			append(  0x9F05, "Application Discretionary Data");
			append(  0x9F06, "Application Identifier (AID) – terminal");
			append(  0x9F07, "Application Usage Control (AUC)");
			append(  0x9F08, "Application Version Number");
			append(  0x9F09, "Application Version Number (Default: 00 02 )");
			append(  0x9F0B, "Cardholder Name Extended");
			append(  0x9F0D, "Issuer Action Code - Default");
			append(  0x9F0E, "Issuer Action Code - Denial");
			append(  0x9F0F, "Issuer Action Code - Online");
			append(  0x9F10, "Issuer Application Data (IAD)");
			append(  0x9F11, "Issuer Code Table Index");
			append(  0x9F12, "Application Preferred Name");
			append(  0x9F13, "Last Online Application Transaction Counter (ATC) Register");
			append(  0x9F14, "Lower Consecutive Offline Limit");
			append(  0x9F15, "Merchant Category Code");
			append(  0x9F16, "Merchant Identifier");
			append(  0x9F17, "Personal Identification Number (PIN) Try Counter");
			append(  0x9F18, "Issuer Script Identifier");
			append(  0x9F19, "Deleted (see 9F49)");
			append(  0x9F1A, "Terminal Country Code");
			append(  0x9F1B, "Terminal Floor Limit");
			append(  0x9F1C, "Terminal Identification");
			append(  0x9F1D, "Terminal Risk Management Data");
			append(  0x9F1E, "Interface Device (IFD) Serial Number");
			append(  0x9F1F, "Track 1 Discretionary Data");
			append(  0x9F20, "Track 2 Discretionary Data");
			append(  0x9F21, "Transaction Time (HHMMSS )");
			append(  0x9F22, "Certification Authority Public Key Index");
			append(  0x9F23, "Upper Consecutive Offline Limit");
			append(  0x9F26, "Application Cryptogram (AC)");
			append(  0x9F27, "Cryptogram Information Data (CID)");
			append(  0x9F29, "Extended Selection");
			append(  0x9F2A, "Kernel Identifier");
			append(  0x9F2D, "Integrated Circuit Card (ICC) PIN Encipherment Public Key Certificate");
			append(  0x9F2E, "Integrated Circuit Card (ICC) PIN Encipherment Public Key Exponent");
			append(  0x9F2F, "Integrated Circuit Card (ICC) PIN Encipherment Public Key Remainder");
			append(  0x9F32, "Issuer Public Key Exponent");
			append(  0x9F33, "Terminal Capabilities (see below)");
			append(  0x9F34, "Cardholder Verification Method (CVM) Results");
			append(  0x9F35, "Terminal Type (see below)");
			append(  0x9F36, "Application Transaction Counter (ATC)");
			append(  0x9F37, "Unpredictable Number");
			append(  0x9F38, "Processing Options Data Object List (PDOL)");
			append(  0x9F39, "POS Entry Mode (Default: 07)");
			append(  0x9F3A, "Amount, Reference Currency");
			append(  0x9F3B, "Application Reference Currency");
			append(  0x9F3C, "Transaction Reference Currency Code");
			append(  0x9F3D, "Transaction Reference Currency Exponent");
			append(  0x9F40, "Additional Terminal Capabilities (see below)");
			append(  0x9F41, "Transaction Sequence Counter");
			append(  0x9F42, "Application Currency Code");
			append(  0x9F43, "Application Reference Currency Exponent");
			append(  0x9F44, "Application Currency Exponent");
			append(  0x9F45, "Data Authentication Code");
			append(  0x9F46, "Integrated Circuit Card (ICC) Public Key Certificate");
			append(  0x9F47, "Integrated Circuit Card (ICC) Public Key Exponent");
			append(  0x9F48, "Integrated Circuit Card (ICC) Public Key Remainder");
			append(  0x9F49, "Dynamic Data Authentication Data Object List (DDOL)");
			append(  0x9F4A, "Static Data Authentication Tag List (SDA)");
			append(  0x9F4B, "Signed Dynamic Application Data (SDAD)");
			append(  0x9F4C, "ICC Dynamic Number");
			append(  0x9F4D, "Log Entry");
			append(  0x9F4E, "Merchant Name and Location");
			append(  0x9F4E, "Merchant Name and Location");
			append(  0x9F4F, "Log Format");
			append(  0x9F50, "Offline Accumulator Balance");
			append(  0x9F51, "Application Currency Code");
			append(  0x9F52, "Application Default Action (ADA)");
			append(  0x9F53, "Transaction Category Code");
			append(  0x9F54, "DS ODS Card");
			append(  0x9F55, "Geographic Indicator");
			append(  0x9F56, "Issuer Authentication Indicator");
			append(  0x9F57, "Issuer Country Code");
			append(  0x9F58, "Consecutive Transaction Counter Limit (CTCL)");
			append(  0x9F59, "Consecutive Transaction Counter Upper Limit (CTCUL)");
			append(  0x9F5A, "Application Program Identifier (Program ID)");
			append(  0x9F5B, "Issuer Script Results");
			append(  0x9F5C, "Magstripe Data Object List (MDOL)");
			append(  0x9F5D, "Available Offline Spending Amount (AOSA)");
			append(  0x9F5D, "Application Capabilities Information (ACI)");
			append(  0x9F5E, "Consecutive Transaction International Upper Limit (CTIUL)");
			append(  0x9F5E, "DS ID");
			append(  0x9F5F, "DS Slot Availability");
			append(  0x9F60, "CVC3 (Track1)");
			append(  0x9F61, "CVC3 (Track2)");
			append(  0x9F62, "PCVC3 (Track1)");
			append(  0x9F64, "NATC (Track1)");
			append(  0x9F65, "PCVC3 (Track2)");
			append(  0x9F66, "PUNATC (Track2)");
			append(  0x9F67, "NATC (Track2)");
			append(  0x9F68, "Card Additional Processes");
			append(  0x9F69, "UDOL");
			append(  0x9F6A, "Unpredictable Number (Numeric)");
			append(  0x9F6B, "Track 2 Data");
			append(  0x9F6C, "Card Transaction Qualifiers (CTQ)");
			append(  0x9F6D, "Mag-stripe Application Version Number (Reader)");
			append(  0x9F6E, "Third Party Data");
			append(  0x9F6E, "Terminal Transaction Capabilities");
			append(  0x9F6F, "DS Slot Management Control");
			append(  0x9F70, "Protected Data Envelope 1");
			append(  0x9F71, "Protected Data Envelope 2");
			append(  0x9F72, "Protected Data Envelope 3");
			append(  0x9F73, "Protected Data Envelope 4");
			append(  0x9F74, "Protected Data Envelope 5");
			append(  0x9F75, "Unprotected Data Envelope 1");
			append(  0x9F76, "Unprotected Data Envelope 2");
			append(  0x9F77, "Unprotected Data Envelope 3");
			append(  0x9F78, "Unprotected Data Envelope 4");
			append(  0x9F79, "Unprotected Data Envelope 5");
			append(  0x9F7A, "VLP Terminal Support Indicator");
			append(  0x9F7B, "VLP Terminal Transaction Limit");
			append(  0x9F7C, "Customer Exclusive Data (CED)");
			append(  0x9F7D, "DS Summary 1");
			append(  0x9F7F, "DS Unpredictable Number");
			append(  0xBF0C, "File Control Information (FCI) Issuer Discretionary Data");
			append(  0xBF50, "Visa Fleet - CDO");
			append(  0xBF60, "Integrated Data Storage Record Update Template");
			append(  0xDF01, "ApplePay VAS Protocol");
			append(  0xDF02, "ApplePay VAS Failure Report");
			append(  0xDF10, "Terminal Languages Supported");
			append(  0xDF10, "Multi Language (Default: “enfr”)");
			append(  0xDF11, "Enable Transaction Logging");
			append(  0xDF13, "Terminal Action Code - Default");
			append(  0xDF14, "Terminal Action Code - Denial");
			append(  0xDF15, "Terminal Action Code - Online");
			append(  0xDF17, "Threshold Value for Biased Random Selection");
			append(  0xDF18, "Target Percentage to be Used for Random Selection");
			append(  0xDF19, "Maximum Target Percentage to be used for Biased Random Selection");
			append(  0xDF1F, "Last 4 digits of Primary Account Number (PAN)");
			append(  0xDF21, "Issuer Script Results");
			append(  0xDF22, "Force Online (1-Enable, 0-Disable)");
			append(  0xDF25, "Default DDOL (1-Enable, 0-Disable)");
			append(  0xDF26, "Revocation List Support (Default: Enable - 1)");
			append(  0xDF27, "Exception File Support (Default: Disable - 0)");
			append(  0xDF28, "Default TDOL");
			append(  0xDF29, "Terminal Capabilities - CVM Required");
			append(  0xDF2A, "Threshold Value for Biased Random Selection (Interac)");
			append(  0xDF2B, "Maximum Target Percentage for Biased Random Selection (Interac)");
			append(  0xDF2C, "Target Percentage for Random Selection (Interac)");
			append(  0xDF30, "Track Data Source");
			append(  0xDF31, "DD Card Track 1");
			append(  0xDF32, "DD Card Track 2");
			append(  0xDF33, "Interac Receipt Required");
			append(  0xDF34, "TTK Customer -  Firmware Version");
			append(  0xDF40, "Message to be displayed by EMV Kernel on “PIN Try Limit Exceeded” condition");
			append(  0xDF41, "Message to be displayed by EMV Kernel on “Last PIN Try” condition");
			append(  0xDF42, "Message to be displayed by EMV Kernel on “Please Try Again” condition");
			append(  0xDF43, "Message to be displayed by EMV Kernel on “Call Your Bank” condition");
			append(  0xDF45, "GMEDS Secret Keys");
			append(  0xDF46, "GMAD MIDs");
			append(  0xDF47, "ISIS Read Cmd Data");
			append(  0xDF48, "ISIS Write Data");
			append(  0xDF49, "ISIS Transaction Data");
			append(  0xDF4A, "TTK Customer - Current KSN of Data encryption Key");
			append(  0xDF4B, "TTK Customer - MSR all track data");
			append(  0xDF4C, "TTK Customer -  Masked PAN");
			append(  0xDF4D, "TTK Customer -  Additional POS Info");
			append(  0xDF4E, "Polling Options");
			append(  0xDF4F, "TTK Customer -  Fallback Reason");
			append(  0xDF50, "Special Flow");
			append(  0xDF51, "Amex Terminal Capability");
			append(  0xDF52, "Transaction CVM");
			append(  0xDF55, "RID");
			append(  0xDF56, "Activate Trans for DESFireViVOComm Flows");
			append(  0xDF57, "Reader Primary Language");
			append(  0xDF57, "2nd usage: Remaining Candidates");
			append(  0xDF58, "Reader Secondary Language");
			append(  0xDF5A, "TLV Exclusion List");
			append(  0xDF5B, "Terminal Entry Capability");
			append(  0xDF5C, "RF Deactivate Period");
			append(  0xDF5D, "D-PAS Issuer Script Response status");
			append(  0xDF5E, "Transaction Timing Information");
			append(  0xDF5F, "Encrypted PAN for remote PIN Pad");
			append(  0xDF60, "Product ID");
			append(  0xDF61, "Processor ID");
			append(  0xDF61, "CVMRequiredLimit_JCBScheme");
			append(  0xDF62, "Main Firmware Build ID");
			append(  0xDF63, "CB Enhanced DDA Indicator (same block as DF03)");
			append(  0xDF64, "CB Wave 2 CVM Requirements (same block as DF04)");
			append(  0xDF65, "Build ID Num (Cxx)");
			append(  0xDF65, "CB Display Offline Funds Indicator (same block as DF05)");
			append(  0xDF65, "Serial heartbeat Required");
			append(  0xDF66, "SVN Number");
			append(  0xDF66, "CB Terminal Type (same block as 9F35)");
			append(  0xDF66, "Display Unsupported Card");
			append(  0xDF68, "Enable/Disable STOP command processing");
			append(  0xDF69, "ConfigureProprietaryTags");
			append(  0xDF6A, "Enable/Disable Comm Error Recovery");
			append(  0xDF6C, "Cubic FTP Phase 2 Mode Options");
			append(  0xDF6D, "Cubic Mode 3 Match AID");
			append(  0xDF6E, "Cubic Fixed Fare Amounts");
			append(  0xDF6F, "Cubic Timestamp Data");
			append(  0xDF70, "Loyalty Program ID");
			append(  0xDF70, "Generic Name String");
			append(  0xDF71, "Value Added Tax 1");
			append(  0xDF71, "Generic Numeric");
			append(  0xDF72, "Value Added Tax 2");
			append(  0xDF72, "Generic Specification String");
			append(  0xDF73, "Merchant Category Code");
			append(  0xDF73, "Generic Implementation String");
			append(  0xDF74, "Discover Optional Features");
			append(  0xDF75, "Communications Error Message Delay");
			append(  0xDF76, "TVR from GenAC");
			append(  0xDF77, "ViVOpay MSR Custom Data Output Tag");
			append(  0xDF78, "MC Timing Performance Enable");
			append(  0xDF79, "Card Disable Mask");
			append(  0xDF7A, "Card Disable Interval");
			append(  0xDF7B, "Serial Port (UART) Inter-character Timeout Period");
			append(  0xDF7C, "Auto Switch Feature");
			append(  0xDF7D, "Track Formatting Feature");
			append(  0xDF7F, "Improved Collision Detection & Media Removal Feature");
			append(  0xFF69, "ViVOpay Proprietary Tag List");
			append(  0xFF70, "Serial Finite State Machine Version");
			append(  0xFF71, "Transaction Finite State Machine Version");
			append(  0xFF72, "System Information Suite");
			append(  0xFF73, "Serial Protocol Version");
			append(  0xFF74, "Serial Protocol Suite");
			append(  0xFF75, "L1 Paypass Version");
			append(  0xFF76, "L1 LCR Version");
			append(  0xFF77, "L2 Card App Version");
			append(  0xFF78, "L2 Card App Suite");
			append(  0xFF79, "GMEDs Data");
			append(  0xFF79, "User Experience Version");
			append(  0xFF7A, "User Experience Suite");
			append(  0xFF7B, "ViVOtech Proprietary Suite");
			append(  0xFF7C, "VIUDS Scheme IDs Supported");
			append(  0xFF7D, "VIUDS Scheme ID Selection Criteria");
			append(  0xFFE0, "Registered Application Provider Identifier (RID)");
			append(  0xFFE1, "Partial Selection Allowed");
			append(  0xFFE2, "Application Flow");
			append(  0xFFE3, "Selection Features - GR 1.2.10");
			append(  0xFFE4, "Group Number / Fallback Group");
			append(  0xFFE5, "Max AID Length");
			append(  0xFFE6, "AID Disabled");
			append(  0xFFE7, "Interface Support");
			append(  0xFFE8, "Exclude from Processing");
			append(  0xFFE9, "Kernel ID Transaction Type Group List");
			append(  0xFFEA, "Default Kernel ID");
			append(  0xFFF0, "Specific Features Switch");
			append(  0xFFF1, "Terminal Contactless Transaction Limit");
			append(  0xFFF2, "Terminal IFD");
			append(  0xFFF3, "Application Capability");
			append(  0xFFF4, "Visa Reader Risk Flags");
			append(  0xFFF6, "Torn Transaction Log Clean Interval (minutes)");
			append(  0xFFF7, "Burst Mode");
			append(  0xFFF8, "UI Scheme");
			append(  0xFFF9, "LCD Font Size");
			append(  0xFFFA, "LCD Delay Time");
			append(  0xFFFB, "Language Option for LCD");
			append(  0xFFFC, "Force MagStripe");
			append(0xDF891B, "Poll Mode");
			append(0xDF891C, "Interac Retry Limit");
			append(0xDFDE04, "MSR Encryption Option");
			append(0xDFEE0C, "PPSE Terminate Flags");
			append(0xDFEE12, "KID");
			append(0xDFEE15, "Application Selection Indicator");
			append(0xDFEE16, "DUKPT Key or MKSK Select for Online PIN Encrypted");
			append(0xDFEE17, "ICC Terminal Entry Mode");
			append(0xDFEE18, "MSR Terminal Entry Mode");
			append(0xDFEE19, "Online DOL");
			append(0xDFEE1A, "Output data element");
			append(0xDFEE1B, "Authorization Request data elements");
			append(0xDFEE1E, "Contact Terminal Configuration (see below)");
			append(0xDFEE1F, "Issuer script device limit, Range: 0~255 (Default: 128)");
			append(0xDFEE20, "ICC Power on detect waiting time. (Unit: Sec) (Default: 60S)");
			append(0xDFEE21, "ICC L1 waiting time. (Unit: Sec)(Default: 10 S)");
			append(0xDFEE22, "Driver (Menu, Get PIN, Get MSR) Timeout. (Unit: Sec) (see below)");
			append(0xDFEE23, "MSR Track Data");
			append(0xDFEE24, "Force Acceptance (Default: 00)");
			append(0xDFEE25, "ICC Response Code");
			append(0xDFEE26, "Encryption Status Information");
			append(0xDFEE27, "MSR Control");
			append(0xDFEF1A, "TLV available");
			append(0xDFEF1A, "Encrypted Sensitive Tags");
			append(0xDFEF1A, "Auto Authenticate");
			append(0xDFEF20, "MAC option in reponse data");
			append(0xDFEF21, "BIN");
			append(0xDFEF22, "AID");
			append(0xDFEF23, "HMAC");
			append(0xDFEF24, "HMAC KSN");
			append(0xDFEF25, "Output Data Format Select");
			append(0xDFEF26, "MSR fallback");
			append(0xDFEF27, "Online capability");
			append(0xDFEF28, "Disable Encrypt ON");
			append(0xDFEF2C, "Terminal AID List");
			append(0xDFEF2E, "Terminal Transaction Log");
			append(0xDFEF2F, "CUP configuration");
			append(0xDFEF30, "White List");
			append(0xDFEF31, "Black List");
			append(0xDFEF32, "Auto-Switch");
			append(0xDFEF34, "Antenna Detection Switch");
			append(0xDFEF35, "Communications Watchdog Period");
			append(0xDFEF36, "Media Control & Status Tracking");
			append(0xDFEF37, "Interface Select");
			append(0xDFEF38, "Timeout for Next Command");
			append(0xDFEF39, "Network Indicate");
			append(0xDFEF3A, "Reader Behavior Mode");
			append(0xDFEF3B, "Autopoll Transaction Separation Interval");
			append(0xDFEF40, "Ascii-code encryption Tag57 TLV");
			append(0xDFEF41, "MAC Verification Data for SRED");
			append(0xDFEF42, "MAC Verification KSN for SRED");
			append(0xDFEF43, "Local TZ/DST information");
			append(0xDFEF44, "Combination Options");
			append(0xDFEF45, "Removal Timeout");
			append(0xDFEF46, "ACT Pass Response DOL");
			append(0xDFEF47, "CDA Hash Input");
			append(0xDFEF48, "Indicate - retrieve transaction result again due to Output RAM is Not enough");
			append(0xDFEF49, "Outcome Parameter Set");
			append(0xDFEF4A, "User Interface Request Data");
			append(0xDFEF4B, "MSR Equivalent Data Option");
			append(0xDFEF4C, "MSR Equivalent Data Track Lengths");
			append(0xDFEF4D, "MSR Equivalent Data");
			append(0xDFEF4E, "ACT MSD Response DOL");
			append(0xDFEF4F, "ACT Decline Response DOL");
			append(0xDFEF50, "Terminal Interchange Profile (JCB)");
			append(0xDFEF51, "Bypass EMV Completion Output");
			append(0xDFEF52, "Re-FallBack  times");
			append(0xDFEF53, "Dynamic Reader Limits");
			append(0xDFEF54, "SmartTap AID Index");
			append(0xDFEF55, "Kernel Specific Features");
			append(0xDFEF56, "Retry Limit");
			append(0xDFEF57, "PPSE Terminate Flags");
			append(0xDFEF59, "Terminal Data Setting - Default Amount");
			append(0xDFEF5A, "Terminal Data Setting - Tags to Return");
			append(0xDFEF5B, "Mask for Tag5A");
			append(0xDFEF5C, "Mask for Tag56");
			append(0xDFEF5D, "Mask for Tag57");
			append(0xDFEF5E, "Mask for Tag9F6B");
			append(0xDFEF5F, "Mask for TagFFEE13");
			append(0xDFEF60, "Mask for TagFFEE14");
			append(0xDFEF61, "Error Code");
			append(0xDFEF62, "Allow MSR Swipe data from ICC Card");
			append(0xDFEF63, "Tags To Read Yet");
			append(0xDFEF64, "Referral Timeout");
			append(0xDFEF6E, "USB-KB Output Data Postfix");
			append(0xDFEF6F, "Inter-character Delay for USB-KB Interface");
			append(0xDFEF70, "PISCES dual interface interference prevention mechanism fine-tune parameters");
			append(0xDFEF71, "Waiting ICC insert time");
			append(0xDFEF72, "Pre-poll card mechanism control in ACT cmd & config setting");
			append(0xDFEF73, "Transaction Message Type");
			append(0xDFEF74, "Reference amplitude value");
			append(0xDFEF75, "Reference delta value");
			append(0xDFEF76, "Transaction Interface Type to activate");
			append(0xDFEF77, "Timeout for waiting next command");
			append(0xDFEF78, "EMV contact L2 display messages option");
			append(0xDFEF79, "PIN block format (when TDES)");
			append(0xDFEF7A, "Enable Apple Pay Check");
			append(0xDFEF7B, "Apple Pay Status");
			append(0xDFEF7C, "Track Bit Encoding");
			append(0xDFEF7D, "Re-power on times");
			append(0xDFEF7E, "Fallback response code list");
			append(0xFFEE01, "ViVOpay TLV Group Tag");
			append(0xFFEE02, "ViVOpay Pre-PPSE Special Flow Group Tag");
			append(0xFFEE03, "ViVOpay Post-PPSE Special Flow Group Tag");
			append(0xFFEE04, "M/Chip3 Intermediate Message Data");
			append(0xFFEE05, "M/Chip3 Intermediate Message Marker");
			append(0xFFEE06, "ApplePay VAS Container");
			append(0xFFEE07, "Encrypted Sensitive Tags");
			append(0xFFEE08, "Masked Tags");
			append(0xFFEE0A, "BIN Range");
			append(0xFFEE0B, "AID Range");
			append(0xFFEE0C, "White List");
			append(0xFFEE10, "ViVOpay MChip Group Tag");
			append(0xFFEE11, "ViVOpay Discover Group Tag");
			append(0xFFEE12, "KID");
			append(0xFFEE12, "Cash Reader Risk Record");
			append(0xFFEE13, "Track 1 Data");
			append(0xFFEE13, "Cashback Reader Risk Record");
			append(0xFFEE14, "Track 2 Data");
			append(0xFFEE14, "DRL Record 1");
			append(0xFFEE15, "DRL Record 2");
			append(0xFFEE16, "DRL Record 3");
			append(0xFFEE17, "DRL Record 4");
			append(0xFFEE18, "Tags To Write Yet Before GenAC");
			append(0xFFEE19, "Tags To Write Yet After GenAC");
			append(0xFFEE1A, "Terminal App DET Data");
			append(0xFFEE1C, "Unpredictable Number Range");
			append(0xFFEE1D, "Sensitive Data Mask");
			append(0xFFEE1E, "Group 0 Initialize Flag ");
			append(0xFFEE1F, "Error Code Table");
			append(0xFFEE20, "Restart Deactivation Time");
		}
	};

	static CData Data;
}

//--------------------------------------------------------------------------------
